
theme: minima
author:JJBYTE-NETIZEN
Commit your changes.
ll request, set base: main and compare:my-pages.
Wait about 20 seconds then refresh this page (the one you're following instructions from). GitHub Actions will automatically update to the next step.
